### ISSUE TITLE
Increase width to 280 to accommodate 4-digit channel numbers

### ISSUE THREAD

**Issue by bshensky** [pkscout/skin.estuary.matrix.pkscout.mod#1]
https://github.com/pkscout/skin.estuary.matrix.pkscout.mod/blob/c78c1fa596a67d720303e020a72ae3630355a935/xml/DialogSeekBar.xml#L299

Perhaps also set <align>left</align> rather than center the box.

I have a set of channels in the 6000 and 7000 series.  This mod allows these "wide" channel strings to show in their entirety.

Thanks for all you do!

**Comment by pkscout** [comment]
The default skin has it set to center, and I'm trying to make only the minimum necessary changes for the updates so that this skin will mostly behave like Estuary.
