### ISSUE TITLE
Custom Main Menu items

### ISSUE THREAD

**Issue by apothegm** [pkscout/skin.estuary.matrix.pkscout.mod#2]
Any chance of there ever being custom main menu items like we see on other skins?

For example, if I want to link directly to an addon, or have a widget of addon's submenu items?

Unfortunately Estuary MOD V2 by Guilouz does not support Kodi 19.

**Comment by pkscout** [comment]
Nope. This mod just allows you to customize the existing options. To do what you want the entire skin would have to be rewritten to support the skinshortcuts addon. That is well beyond my ability or time.
